### ISSUE TITLE
support for STM8L050

### ISSUE THREAD

**Issue by mackelec** [stm32duino/Arduino_Core_STM8#11]
I'd like to see support added for the STM8L050.  Its a nice little 8 pin uproc with 12ADC , and very low power.  I see Cosmic support the STM8L051F3 which is similar but 20 pin.

**Comment by VVESTM** [comment]
As mentioned in a previous issue, no plan to add new board on our side for now. Any help and PR is welcomed.

**Comment by fpistm** [comment]
Added to to the request list: #15
