### ISSUE TITLE
Support Mac

### ISSUE THREAD

**Issue by sabas1080** [stm32duino/Arduino_Core_STM8#14]
Hi

Please add support for Mac

I can help you for testing

**Comment by fpistm** [comment]
Hi @sabas1080 
as mentioned in the README.md:

> Cosmic compiler, allowing to compile c++ source code on stm8 family (http://www.cosmic-software.com/)
> For now, the solution is running on Windows only.

While no compiler available for this host it would not be possible.

**Comment by sabas1080** [comment]
@fpistm can this help?

https://github.com/tenbaht/sduino/tree/development/sduino/tools/macosx

**Comment by fpistm** [comment]
Unfortunately not.

The main advantage of the cosmic compiler is that it provides C++ compiler. In that case you are able to use Arduino library without converting it to C.
sduino is not able to build C++, you have to convert it in C.

**Comment by fpistm** [comment]
While no C++ compiler available for STM8 for Linux/Mac this will not be possible.
I close it as considered as answered.

**Comment by rtek1000** [comment]
https://tenbaht.github.io/sduino/developer/compiling-the-tools/

**Comment by rtek1000** [comment]
https://github.com/stm32duino/Arduino_Core_STM8/issues/42
