### ISSUE TITLE
Miss json file in it

### ISSUE THREAD

**Issue by Sparkle286** [stm32duino/Arduino_Core_STM8#17]
https://github.com/stm32duino/BoardManagerFiles/raw/master/STM8/package_stm8_index.json

Hi,
the folder miss this json file, please check.
Many thanks for your hardwork.

Best Regards,
Mark

**Comment by fpistm** [comment]
@Sparkle286 
The link is valid.
So don't know what issue you had. Proxy?

**Comment by fpistm** [comment]
Hi @Sparkle286 
The JSON file is valid so issue comes from your env.
