### ISSUE TITLE
Undeclared identifier 'int64_t' on smt8L

### ISSUE THREAD

**Issue by tcampos123** [stm32duino/Arduino_Core_STM8#18]
Hello, I'm using the Arduino IDE to work with the STM8 Core card based on stm8l152R8. I'm having a problem using a lmic library to work with Lorawan. "use of undeclared identifier 'int64_t'". How can I declare a variable using int64_t?

**Comment by VVESTM** [comment]
Hello,
As this question is compiler oriented, as mentionned in [ReadMe.md](https://github.com/stm32duino/Arduino_Core_STM8#troubleshooting-and-known-issues), you can send a mail to Cosmic.

**Comment by fpistm** [comment]
No feedback from user. Don't know if user contact cosmic.
