### ISSUE TITLE
Hi, in your Arduino repo's, do you don't have any examples...as a simple blinky. Just to get started to see that the chain is ok. Just a blink.

### ISSUE THREAD

**Issue by jabadabado** [stm32duino/Arduino_Core_STM8#20]
Hi, in your Arduino repo's, do you don't have any examples...as a simple blinky. Just to get started to see that the chain is ok. Just a blink.

**Comment by fpistm** [comment]
Hi, 
Simply use the Blink.ino from the Arduino IDE.
