### ISSUE TITLE
STM8S003F3P6 Board Variant

### ISSUE THREAD

**Issue by noeldiviney** [stm32duino/Arduino_Core_STM8#28]
Hi frederick,

Any plans to support the STM8S003F3P6 as a Arduino Board variant?

Best regards and hoping that you are keeping safe,

Noel Diviney.

**Comment by fpistm** [comment]
Hi @noeldiviney 

Currently, there is no plan to add new board. The only planned activity is to make a new release to fix the issue with Arduino IDE 1.8.13.

I've added your request to the new variant request list #15 

Thanks and hoping that you are keeping safe too.
