### ISSUE TITLE
ERROR : use of undeclared identifier '_asm' and acces to low power modes / functions & RTC IRQ handler implementation

### ISSUE THREAD

**Issue by 0x0fe** [stm32duino/Arduino_Core_STM8#34]
Hello,
the STM8L serie is pretty much purposed to ultra low power designs, sadly, this core doesnt provide any example of available APIs to use neither RTC, low power mode and implement RTC IRQs.
Besides, when i tried to call halt(); from the hal, i get 

```
C:\Users\xxxx\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm8\1.0.0\system\Drivers\STM8Lxx_StdPeriph_Driver\inc/stm8l15x.h:2925:18: note: expanded from macro 'halt'
 #define halt() {_asm("halt\n");} /*!<Halt */
(...)
use of undeclared identifier '_asm'
```
so, could we have minimum examples for ultra low power modes and RTC, and also how we should implement/handle the IRQs of the hal, in particular the RTC IRQ.

**Comment by fpistm** [comment]
Hi,

you should try to contact Cosmic support to know why _asm is not supported: support@cosmic.fr

**Comment by 0x0fe** [comment]
For that part, i found out, it is a linking issue in arduino core apparently, _asm wont work in cpp files (nor in ino file) even if used inside a function declared as extern "C", however, when used it in a .c file then i can call it without error.

As for teh second part of the question, can we have at least a minimal example for active halt with RTC or interrupt wake up? i have tried to use the HAL example and it never wakes, besides the LCD is shut down, meaning its not in active halt, but in halt.

![image](https://user-images.githubusercontent.com/89607149/197475345-cdb80a73-a9fa-46e1-a155-5f87fe934dc7.png)

![image](https://user-images.githubusercontent.com/89607149/197475468-2463510a-f7e4-479c-a935-4c1c2eca18ba.png)
