### ISSUE TITLE
is this project still supported?

### ISSUE THREAD

**Issue by aldolo69** [stm32duino/Arduino_Core_STM8#40]
At the moment the compiler activation seems impossible.

**Comment by LMESTM** [comment]
Can you ne more specific ?
We got below feedback from compiler team:
If the Customer problem is that he did not receive the email with the license, the best thing to do is try again (and check in the spam folder and/or other filters that sometimes block emails generated automatically like the one above). If it is something else, please provide more details

**Comment by aldolo69** [comment]
a video in yt pointed me in the right direction. the license ended up in the spam folder. a 1y license does no provide the right confidence for an hobby project so i'm  giving up.
