### ISSUE TITLE
Internal pull-down on STM8L052

### ISSUE THREAD

**Issue by 0x0fe** [stm32duino/Arduino_Core_STM8#41]
I need to clarify wether pull-down is possible on STM8L052 because i got conflicting informations from the HAL and from the RM.
The RM seems to tell that we can use internal pull-up or pull-down, with 400K and 10K:

![image](https://user-images.githubusercontent.com/89607149/220354233-34735848-f82c-48ab-b7d2-4e1fbb49e4e2.png)

the HAL on the other hand, explicitely mention we can only use pull-up

https://github.com/stm32duino/Arduino_Core_STM8/blob/784261b369b407612acca8ac2d39e0d86f5f4468/system/Drivers/STM8Lxx_StdPeriph_Driver/src/stm8l15x_gpio.c#L15

so, what is correct? Can we enable pull-down of 10K or 400K on an arbitrary GPIO?
Thank you in advance.

**Comment by fpistm** [comment]
Looking at the RM, this is not link to GPIO but to Routing interface (RI).
![image](https://user-images.githubusercontent.com/20641798/220373068-5388cff0-f238-4682-a1f3-038237ad188b.png)

**Comment by 0x0fe** [comment]
i see, so it would only apply to inputs routed to TIM capture or ADC?

**Comment by fpistm** [comment]
> i see, so it would only apply to inputs routed to TIM capture or ADC?

Don't know. You should ask such question on ST community.
