### ISSUE TITLE
sdcc

### ISSUE THREAD

**Issue by tomaskovacik** [stm32duino/Arduino_Core_STM8#6]
just curious, why not use sdcc compiler?

**Comment by VVESTM** [comment]
When we started, SDCC was not supporting C++. 
Cosmic is supported by ST for stm8 and we worked with them to adapt it for Arduino.

**Comment by tomaskovacik** [comment]
So only windows support?On 13 May 2019 15:26, Vincent VERON <notifications@github.com> wrote:When we started, SDCC was not supporting C++.
Cosmic is supported by ST for stm8 and we worked with them to adapt it for Arduino.

**Comment by VVESTM** [comment]
yes, stm8 support in Arduino is only valid for windows.

**Comment by tomaskovacik** [comment]
I was just curious about future. thx for ans.
