### ISSUE TITLE
Support for STM8S103/003

### ISSUE THREAD

**Issue by mcer12** [stm32duino/Arduino_Core_STM8#7]
Hello, is there any possibility to add support for the small stm8s103f3p6 and stm8s003f3p6 ?

**Comment by VVESTM** [comment]
Hello @mcer12,
There is no plan do it on our side for now. Do you need this for a specific project ? 
Normaly, stm8s103 and stm8s003 are supported by the SPL we used. So adding those 2 boards should consist to add 2 new variants. You can use what was done for stm8s208 (Arduino_Core_STM8/variants/NUCLEO_8S208RB/).
Any PR is welcome...

**Comment by mcer12** [comment]
I see this as very useful because the stm8s103 and  stm8s003 are arguably the most common and cheapest chips. I use https://github.com/tenbaht/sduino but it's not compatible with other libraries. I tried to add a new variant but it didn't compile so I gave up as I don't really know what I'm doing... I would leave this thread open if anyone would like to contribute.

**Comment by rishabhrpg** [comment]
do this library support stm8s003 ? as of now if not can it add?

**Comment by VVESTM** [comment]
As mentioned previously, no plan to add new board on our side for now. Any help and PR is welcomed.

**Comment by fpistm** [comment]
Added to to the request list: #15

**Comment by MadZoids** [comment]
> Hello @mcer12,
> There is no plan do it on our side for now. Do you need this for a specific project ?
> Normaly, stm8s103 and stm8s003 are supported by the SPL we used. So adding those 2 boards should consist to add 2 new variants. You can use what was done for stm8s208 (Arduino_Core_STM8/variants/NUCLEO_8S208RB/).
> Any PR is welcome...

is it the same methods like creating new board for STM32?

**Comment by fpistm** [comment]
Hi @MadZoids 
yes it is quiet the same

**Comment by rtek1000** [comment]
sduino already supports this variant, can't use this information?

Apparently this repository is no longer being updated, more than 3 years without improvement:

https://github.com/tenbaht/sduino
