### ISSUE TITLE
STM8L152R8 board definition

### ISSUE THREAD

**Issue by vbshightime** [stm32duino/Arduino_Core_STM8#8]
what is the board definition for STM8L boards like for Arduino we use ifdef ARDUINO andfor stm32f we use __STM32F1__

**Comment by fpistm** [comment]
Well, your example depends on the core you used for STM32F1.
For a core there is several define which can be used.
The SPL define this `STM8Lxx`
The core define `ARDUINO_ARCH_STM8`
...
